# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Test GitHub Actions with Node.js

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v20
      uses: actions/setup-node@v4
      with:
        node-version: v20
        cache: 'npm'
        
    - name: Setup yarn
      run: npm install -g yarn
    - run: yarn
    - run: yarn test
    - run: yarn build
    - run: yarn test:e2e
    
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: reports/**/*.xml
